spring:
  cache:
    #cache-names: cache1,cache2
    redis:   
      time-to-live: 600000
 #cache 10 min            
      
  redis: 
     host: gdc-nba-api-01.offline.hupu.com
     port: 6379
     password: 
     timeout: 3000
     
      
      
